baseURL = "https://commons.garden/"
languageCode = "en-us"
title = "Commons Garden"
description = "Knowledge Commons"
publishDir = "docs"
category = ["article", "initiative", "spec", "team", "volunteer", "wireframe", "note"]