baseURL = "https://commons-garden.github.io"
repo = "https://github.com/commons-garden/commons-garden.github.io"
languageCode = "en-us"
description = "Enhancing knowledge commons"
title = "commons.garden"
publishDir = "docs"
enableEmoji = true

[taxonomies]
  category = "categories"
  organization = "organizations"
  garderner = "gardeners"
  initiative = "initiatives"

