baseURL = "https://commons.garden"
repo = "https://gitlab.com/commons-garden/commons-garden.gitlab.io"
languageCode = "en-us"
description = "Enhancing knowledge commons"
title = "commons.garden"
publishDir = "docs"
enableEmoji = true

[taxonomies]
  category = "categories"
  organization = "organizations"
  garderner = "gardeners"
  initiative = "initiatives"

