baseURL = "https://commons.garden/"
languageCode = "en-us"
title = "commons.garden"
description = "Enhancing knowledge commons"
publishDir = "public"
category = ["article", "initiative", "spec", "team", "volunteer", "wireframe", "note"]